import type { PlatformModuleManifest } from "@/lib/platform/modules/module-manifest";

export const builtInModuleManifests: readonly PlatformModuleManifest[] = [
  {
    moduleId: "crm-core",
    name: "CRM Core",
    description: "Core customer relationship operations foundation.",
    version: "1.0.0",
    category: "Operations",
    navigationGroup: "Operations",
    permissionGroup: "Communications",
    licenseRequirement: "starter",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: [],
    defaultEnabled: true,
    navigation: [{ label: "CRM", path: "/company/crm", area: "company", group: "Operations", order: 10 }],
    permissions: [{ key: "crm.access", group: "Communications", description: "Access CRM module." }],
    featureFlags: [{ key: "crm", defaultEnabled: true, description: "Enable CRM core." }],
    settings: [{ key: "crm.default_view", defaultValue: "dashboard", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "CRM_ACCESSED", description: "CRM module accessed." }],
    extensionPoints: [{ point: "dashboard.widgets", description: "CRM dashboard widgets." }]
  },
  {
    moduleId: "communications-whatsapp",
    name: "WhatsApp",
    description: "WhatsApp communication channel foundation.",
    version: "1.0.0",
    category: "Communications",
    navigationGroup: "Communications",
    permissionGroup: "Communications",
    licenseRequirement: "starter",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: true,
    navigation: [{ label: "WhatsApp", path: "/company/communications/whatsapp", area: "company", group: "Communications", order: 20 }],
    permissions: [{ key: "whatsapp.access", group: "Communications", description: "Access WhatsApp module." }],
    featureFlags: [{ key: "whatsapp", defaultEnabled: true, description: "Enable WhatsApp communication." }],
    settings: [{ key: "whatsapp.default_provider", defaultValue: "manual", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "WHATSAPP_MODULE_ENABLED", description: "WhatsApp module enabled." }],
    extensionPoints: [{ point: "sidebar.navigation", description: "WhatsApp navigation entries." }]
  },
  {
    moduleId: "ticketing",
    name: "Ticketing",
    description: "Ticketing workflow foundation.",
    version: "1.0.0",
    category: "Operations",
    navigationGroup: "Operations",
    permissionGroup: "Management",
    licenseRequirement: "starter",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "Tickets", path: "/company/tickets", area: "company", group: "Operations", order: 30 }],
    permissions: [{ key: "ticketing.access", group: "Management", description: "Access ticketing module." }],
    featureFlags: [{ key: "ticketing", defaultEnabled: false, description: "Enable ticketing." }],
    settings: [{ key: "ticketing.default_status", defaultValue: "new", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "TICKETING_MODULE_ENABLED", description: "Ticketing module enabled." }],
    extensionPoints: [{ point: "customer.timeline", description: "Ticket timeline entries." }]
  },
  {
    moduleId: "voice",
    name: "Voice",
    description: "Voice communication foundation.",
    version: "1.0.0",
    category: "Communications",
    navigationGroup: "Communications",
    permissionGroup: "Communications",
    licenseRequirement: "professional",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "Voice", path: "/company/communications/voice", area: "company", group: "Communications", order: 40 }],
    permissions: [{ key: "voice.access", group: "Communications", description: "Access voice module." }],
    featureFlags: [{ key: "voice", defaultEnabled: false, description: "Enable voice." }],
    settings: [{ key: "voice.default_provider", defaultValue: "openai", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "VOICE_MODULE_ENABLED", description: "Voice module enabled." }],
    extensionPoints: [{ point: "operator.workspace", description: "Voice workspace actions." }]
  },
  {
    moduleId: "reports",
    name: "Reports",
    description: "Analytics and reports foundation.",
    version: "1.0.0",
    category: "Analytics",
    navigationGroup: "Analytics",
    permissionGroup: "Analytics",
    licenseRequirement: "professional",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "Reports", path: "/company/reports", area: "company", group: "Analytics", order: 50 }],
    permissions: [{ key: "reports.view", group: "Analytics", description: "View reports." }],
    featureFlags: [{ key: "reports", defaultEnabled: false, description: "Enable reports." }],
    settings: [{ key: "reports.default_range", defaultValue: "last_7_days", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "REPORT_VIEWED", description: "Report viewed." }],
    extensionPoints: [{ point: "reports.providers", description: "Report providers." }]
  },
  {
    moduleId: "automation",
    name: "Automation",
    description: "Automation trigger foundation.",
    version: "1.0.0",
    category: "Operations",
    navigationGroup: "Operations",
    permissionGroup: "Management",
    licenseRequirement: "professional",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "Automation", path: "/company/automation", area: "company", group: "Operations", order: 60 }],
    permissions: [{ key: "automation.manage", group: "Management", description: "Manage automation." }],
    featureFlags: [{ key: "automation", defaultEnabled: false, description: "Enable automation." }],
    settings: [{ key: "automation.enabled", defaultValue: true, visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "AUTOMATION_RULE_CHANGED", description: "Automation rule changed." }],
    extensionPoints: [{ point: "automation.triggers", description: "Automation trigger providers." }]
  },
  {
    moduleId: "live-support",
    name: "Live Support",
    description: "Live support channel foundation.",
    version: "1.0.0",
    category: "Customer Relations",
    navigationGroup: "Customer Relations",
    permissionGroup: "Communications",
    licenseRequirement: "professional",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "Live Support", path: "/company/live-support", area: "company", group: "Customer Relations", order: 70 }],
    permissions: [{ key: "live_support.access", group: "Communications", description: "Access live support." }],
    featureFlags: [{ key: "live_support", defaultEnabled: false, description: "Enable live support." }],
    settings: [{ key: "live_support.routing", defaultValue: "round_robin", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "LIVE_SUPPORT_ENABLED", description: "Live support enabled." }],
    extensionPoints: [{ point: "notifications.providers", description: "Live support notifications." }]
  },
  {
    moduleId: "api-access",
    name: "API Access",
    description: "API access foundation.",
    version: "1.0.0",
    category: "Engineering",
    navigationGroup: "Engineering",
    permissionGroup: "Engineering",
    licenseRequirement: "business",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "API Access", path: "/company/api", area: "company", group: "Engineering", order: 80 }],
    permissions: [{ key: "api_access.manage", group: "Engineering", description: "Manage API access." }],
    featureFlags: [{ key: "api_access", defaultEnabled: false, description: "Enable API access." }],
    settings: [{ key: "api_access.rate_limit", defaultValue: 1000, visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "API_ACCESS_CHANGED", description: "API access changed." }],
    extensionPoints: [{ point: "export.providers", description: "API export providers." }]
  },
  {
    moduleId: "integrations",
    name: "Integrations",
    description: "Integration framework foundation.",
    version: "1.0.0",
    category: "Engineering",
    navigationGroup: "Engineering",
    permissionGroup: "Engineering",
    licenseRequirement: "business",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["api-access"],
    defaultEnabled: false,
    navigation: [{ label: "Integrations", path: "/company/integrations", area: "company", group: "Engineering", order: 90 }],
    permissions: [{ key: "integrations.manage", group: "Engineering", description: "Manage integrations." }],
    featureFlags: [{ key: "integrations", defaultEnabled: false, description: "Enable integrations." }],
    settings: [{ key: "integrations.enabled", defaultValue: true, visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "INTEGRATION_CHANGED", description: "Integration changed." }],
    extensionPoints: [{ point: "import.providers", description: "Integration import providers." }]
  },
  {
    moduleId: "ai-assistant",
    name: "AI Assistant",
    description: "AI assistant foundation.",
    version: "1.0.0",
    category: "AI Center",
    navigationGroup: "AI Center",
    permissionGroup: "ProductCenter",
    licenseRequirement: "enterprise",
    requiredPlatformVersion: "0.1.0",
    compatibility: ["0.1.x"],
    breakingChanges: [],
    dependencies: ["crm-core"],
    defaultEnabled: false,
    navigation: [{ label: "AI Assistant", path: "/company/ai-assistant", area: "company", group: "AI Center", order: 100 }],
    permissions: [{ key: "ai_assistant.access", group: "ProductCenter", description: "Access AI assistant." }],
    featureFlags: [{ key: "ai_assistant", defaultEnabled: false, description: "Enable AI assistant." }],
    settings: [{ key: "ai_assistant.mode", defaultValue: "assistive", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "AI_SUGGESTION_ACCEPTED", description: "AI suggestion accepted." }],
    extensionPoints: [{ point: "search.providers", description: "AI search provider." }]
  }
];
