import type { PlatformCapabilityManifest } from "@/lib/platform/capabilities/capability-manifest";

export const builtInCapabilityManifests: readonly PlatformCapabilityManifest[] = [
  {
    capabilityId: "crm.customer-profile",
    moduleId: "crm-core",
    name: "Customer Profile",
    description: "Customer profile capability foundation.",
    version: "1.0.0",
    category: "CRM",
    permissionGroup: "Communications",
    licenseRequirement: "starter",
    dependencies: [],
    defaultEnabled: true,
    permissions: [{ key: "crm.customer_profile.access", group: "Communications", description: "Access customer profiles." }],
    featureFlags: [{ key: "crm.customer_profile", defaultEnabled: true, description: "Enable customer profiles." }],
    settings: [{ key: "crm.customer_profile.default_tab", defaultValue: "overview", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "CUSTOMER_PROFILE_VIEWED", description: "Customer profile viewed." }],
    extensionPoints: [{ point: "customer.timeline", description: "Customer profile timeline entries." }],
    configurationSchema: { defaultTab: "string" }
  },
  {
    capabilityId: "crm.timeline",
    moduleId: "crm-core",
    name: "Timeline",
    description: "Customer timeline capability foundation.",
    version: "1.0.0",
    category: "CRM",
    permissionGroup: "Communications",
    licenseRequirement: "starter",
    dependencies: ["crm.customer-profile"],
    defaultEnabled: true,
    permissions: [{ key: "crm.timeline.access", group: "Communications", description: "Access customer timeline." }],
    featureFlags: [{ key: "crm.timeline", defaultEnabled: true, description: "Enable customer timeline." }],
    settings: [{ key: "crm.timeline.default_filter", defaultValue: "all", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "CUSTOMER_TIMELINE_VIEWED", description: "Customer timeline viewed." }],
    extensionPoints: [{ point: "customer.timeline", description: "Timeline providers." }],
    configurationSchema: { defaultFilter: "string" }
  },
  {
    capabilityId: "crm.notes",
    moduleId: "crm-core",
    name: "Notes",
    description: "Customer notes capability foundation.",
    version: "1.0.0",
    category: "CRM",
    permissionGroup: "Communications",
    licenseRequirement: "starter",
    dependencies: ["crm.customer-profile"],
    defaultEnabled: true,
    permissions: [{ key: "crm.notes.manage", group: "Communications", description: "Manage customer notes." }],
    featureFlags: [{ key: "crm.notes", defaultEnabled: true, description: "Enable customer notes." }],
    settings: [{ key: "crm.notes.visibility", defaultValue: "team", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "CUSTOMER_NOTE_CREATED", description: "Customer note created." }],
    extensionPoints: [{ point: "customer.timeline", description: "Note timeline entries." }],
    configurationSchema: { visibility: "string" }
  },
  {
    capabilityId: "whatsapp.conversations",
    moduleId: "communications-whatsapp",
    name: "Conversations",
    description: "WhatsApp conversation capability foundation.",
    version: "1.0.0",
    category: "Communications",
    permissionGroup: "Communications",
    licenseRequirement: "starter",
    dependencies: ["crm.customer-profile"],
    defaultEnabled: true,
    permissions: [{ key: "whatsapp.conversations.access", group: "Communications", description: "Access WhatsApp conversations." }],
    featureFlags: [{ key: "whatsapp.conversations", defaultEnabled: true, description: "Enable WhatsApp conversations." }],
    settings: [{ key: "whatsapp.conversations.assignment", defaultValue: "manual", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "CONVERSATION_STARTED", description: "Conversation started." }],
    extensionPoints: [{ point: "operator.workspace", description: "Conversation workspace panels." }],
    configurationSchema: { assignment: "string" }
  },
  {
    capabilityId: "whatsapp.routing",
    moduleId: "communications-whatsapp",
    name: "Routing",
    description: "Conversation routing capability foundation.",
    version: "1.0.0",
    category: "Communications",
    permissionGroup: "Communications",
    licenseRequirement: "professional",
    dependencies: ["whatsapp.conversations"],
    defaultEnabled: false,
    permissions: [{ key: "whatsapp.routing.manage", group: "Communications", description: "Manage routing." }],
    featureFlags: [{ key: "whatsapp.routing", defaultEnabled: false, description: "Enable routing." }],
    settings: [{ key: "whatsapp.routing.strategy", defaultValue: "round_robin", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "ROUTING_CHANGED", description: "Routing changed." }],
    extensionPoints: [{ point: "automation.triggers", description: "Routing automation triggers." }],
    configurationSchema: { strategy: "string" }
  },
  {
    capabilityId: "voice.calls",
    moduleId: "voice",
    name: "Calls",
    description: "Voice calls capability foundation.",
    version: "1.0.0",
    category: "Voice",
    permissionGroup: "Communications",
    licenseRequirement: "professional",
    dependencies: ["crm.customer-profile"],
    defaultEnabled: false,
    permissions: [{ key: "voice.calls.access", group: "Communications", description: "Access calls." }],
    featureFlags: [{ key: "voice.calls", defaultEnabled: false, description: "Enable voice calls." }],
    settings: [{ key: "voice.calls.recording", defaultValue: false, visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "VOICE_CALL_STARTED", description: "Voice call started." }],
    extensionPoints: [{ point: "operator.workspace", description: "Voice call actions." }],
    configurationSchema: { recording: "boolean" }
  },
  {
    capabilityId: "reports.analytics",
    moduleId: "reports",
    name: "Analytics",
    description: "Analytics capability foundation.",
    version: "1.0.0",
    category: "Analytics",
    permissionGroup: "Analytics",
    licenseRequirement: "professional",
    dependencies: ["crm.customer-profile"],
    defaultEnabled: false,
    permissions: [{ key: "reports.analytics.view", group: "Analytics", description: "View analytics." }],
    featureFlags: [{ key: "reports.analytics", defaultEnabled: false, description: "Enable analytics." }],
    settings: [{ key: "reports.analytics.default_range", defaultValue: "last_7_days", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "ANALYTICS_VIEWED", description: "Analytics viewed." }],
    extensionPoints: [{ point: "dashboard.widgets", description: "Analytics widgets." }],
    configurationSchema: { defaultRange: "string" }
  },
  {
    capabilityId: "ai.assistant",
    moduleId: "ai-assistant",
    name: "AI Assistant",
    description: "AI assistant capability foundation.",
    version: "1.0.0",
    category: "AI",
    permissionGroup: "ProductCenter",
    licenseRequirement: "enterprise",
    dependencies: ["crm.timeline"],
    defaultEnabled: false,
    permissions: [{ key: "ai.assistant.access", group: "ProductCenter", description: "Access AI assistant." }],
    featureFlags: [{ key: "ai.assistant", defaultEnabled: false, description: "Enable AI assistant." }],
    settings: [{ key: "ai.assistant.mode", defaultValue: "assistive", visibility: "company", scope: "company" }],
    auditEvents: [{ eventType: "AI_SUGGESTION_ACCEPTED", description: "AI suggestion accepted." }],
    extensionPoints: [{ point: "search.providers", description: "AI search provider." }],
    configurationSchema: { mode: "string" }
  }
];
